// This file is autogenerated. Changes will be overwritten.
#include "UVLADIE3JM/moc_ViewCadastros.cpp"
#include "UVLADIE3JM/moc_ViewInicio.cpp"
#include "UVLADIE3JM/moc_ViewPacientes.cpp"
#include "UVLADIE3JM/moc_ViewPacientesMenu.cpp"
#include "UVLADIE3JM/moc_ViewRelatorios.cpp"
#include "UVLADIE3JM/moc_ViewViagens.cpp"
